### ISSUE TITLE
Error when training and testing

### ISSUE THREAD

**Issue by robingong** [WisconsinAIVision/UniversalFakeDetect#18]
Hi, I want to reproduce training and testing. After running:
python train.py --name=clip_vitl14 --wang2020_data_path=datasets/ --data_mode=wang2020  --arch=CLIP:ViT-L/14  --fix_backbone

and some weight files are stored, for exmaple, model_epoch_best.pth. And size of model_epoch_best.pth is about 1.7 GB.

But when I use model_epoch_best.pth for validattion.
python3 validate.py --arch=CLIP:ViT-L/14  --ckpt=pretrained_weights/model_epoch_best.pth --result_folder=clip_vitl14

some error occured:

`Traceback (most recent call last):
  File "validate.py", line 281, in <module>
    model.fc.load_state_dict(state_dict)
  File "/opt/data2/condaEnvs/UniversalFakeDetect/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linear:
        Missing key(s) in state_dict: "weight", "bias". 
        Unexpected key(s) in state_dict: "model", "optimizer", "total_steps".`

**Comment by Stevetich** [comment]
Hi, I have encountered the same problems, have u fixed it?

**Comment by zeezou-isee** [comment]
Me too, could you please tell why?

**Comment by zeezou-isee** [comment]
> Hi, I have encountered the same problems, have u fixed it?

<img width="555" height="151" alt="Image" src="https://github.com/user-attachments/assets/9d596377-63e2-4ff4-a858-884586d4e9db" />

I figure out that you can just load the "model" key to the  model, then it will be fixed.

**Comment by zeezou-isee** [comment]
> Hi, I have encountered the same problems, have u fixed it?

<img width="1040" height="167" alt="Image" src="https://github.com/user-attachments/assets/cfcb1260-e10a-4423-ba5a-7572cd904407" />

Specifically, you can adjust the code in validate.py, line 275 in my way.
